version: "3"

services:
  app:
    build:
      context: .
      target: production
      args:
        - SERVER_PORT=$SERVER_PORT
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - NODE_ENV=prodution
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
