version: '3'

services:
  app:
    build:
      context: .
      target: dev
      args:
        - SERVER_PORT=$SERVER_PORT
    volumes:
      - ./backend/:/app
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - NODE_ENV=prodution
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
   
